# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tomcat Engineering
email: info@tomcat-engineering.com
description: Tomcat Engineering is the trading name of freelance engineering consultants Tom Young and Catherine Cleary.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Tomcat_Engineer
github_username:  tomcat-engineering
page_excerpts: true
header_pages: 
  - 101things.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  tips:
    output: true
    permalink: /101things/:name
